// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfijgxzpxenawwkzzcsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmaWpneHpweGVuYXd3a3p6Y3NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNjMyODMsImV4cCI6MjA2NjkzOTI4M30.1OyCOBNchwqlPnrTEcrpgBD9m-gCt42ODsimja7SmIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});